# Generated by Django 4.2.4 on 2023-08-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField(max_length=11)),
                ('phone', models.IntegerField(max_length=11)),
                ('name', models.CharField(max_length=128)),
                ('birth_date', models.DateField()),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('password_salt', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usr_user',
            },
        ),
    ]
