# Generated by Django 4.2.4 on 2023-08-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='password_salt',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.TextField(),
        ),
    ]
