# Generated by Django 4.2.4 on 2023-08-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usermodel_password_salt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
