version: "3.7"

services:
  database:
    image: postgres:12.7-alpine
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dockerteste
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pw1234
    networks:
      - dev

  backend:
    build: ./finapp
    container_name: "backend"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./finapp/:/usr/src/app/
    ports:
      - 8000:8000
    networks:
      - dev
    depends_on:
      - database
    env_file:
      - ./.env
    stdin_open: true
    tty: true
  
  frontend:
    build: ./frontend
    container_name: "frontend"
    volumes:
      - ./frontend:/app
      - node-modules:/app/node_modules
    networks:
      - dev
    ports:
      - '3000:3000'
    stdin_open: true
    environment:
      - NODE_ENV=development
    depends_on:
      - "backend"
    command:
      npm start
  
  # nginx:
  #   build: ./nginx
  #   ports:
  #       - 8000:8000
  #   depends_on:
  #       - backend

volumes:
  postgres_data:
  node-modules:

networks:
  dev: